services:
  - type: web
    name: quote-generator
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y \
        libpangocairo-1.0-0 \
        libpango-1.0-0 \
        libcairo2 \
        libcairo2-dev \
        libgdk-pixbuf2.0-0 \
        shared-mime-info \
        libffi-dev \
        libssl-dev && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
